### PR TITLE
Various upgrades: node 16, storybook 7, webpack 5

### PR DESCRIPTION
**Pull request by sumnerwarren**

### CODE REVIEW

**Comment by adam-at-brown** [comment]
As far as I can tell, Today@Brown is the only project still using this - it may be worth just copying over the needed components to that repo so this can be retired (maybe?)

**Comment by sumnerwarren** [comment]
> As far as I can tell, Today@Brown is the only project still using this - it may be worth just copying over the needed components to that repo so this can be retired (maybe?)

Unfortunately it's not the only consumer. Three Year Planning uses it and some of the drupal apps ([for example](https://github.com/BrownUniversity/drupal-react-bill-estimator-undergrad/blob/693889abde2512a132444c6725fc029fa6144b25/package.json#L25)) still have it listed as a dependency (whether or not they are using it).

**Comment by adam-at-brown** [comment]
The drupal apps will be fully free of it after the transition to the monorepo - they should be already but will be for certain then; which should be soon.

**Comment by sumnerwarren** [comment]
I would love to get rid of this, but that's not a short-term possibility. Doing the bare minimum upgrades/fixes to allow T@B modernization efforts to continue.

**Review by adam-at-brown — APPROVED** [review]

**Pull request merged**
